### ISSUE TITLE
Drekanoth

### ISSUE THREAD

**Issue by jgheld** [Bamux/Rift-Raid-Alert#1]
It said the time of the fight instead of the name.  Also, it says "dollar player" instead of the name sometimes.

trigger = eng; RoF; Drekanoth of Fate; emote; $player faces imminent Doom!; intercept $player; 0; 0; 0; 0; 0; 0

02:59:35: [Rift Raid Alert] ! Combat Begin -> Drekanoth of Fate
02:59:52: Omegawar faces imminent Doom!
Siri: intercept 02:59:52:
03:00:31: Kaazie faces imminent Doom!
Siri: intercept 03:00:31:
03:01:06: Flamming@Hailol faces imminent Doom!
Siri: intercept 03:01:06:
03:01:52: Berbash faces imminent Doom!
Siri: intercept 03:01:52:
03:02:25: Omegawar faces imminent Doom!
Siri: intercept 03:02:25:
03:03:02: Kaazie faces imminent Doom!
Siri: intercept 03:03:02:

**Comment by Bamux** [comment]
I changed the trigger in the RiftRaidAlert.ini :
trigger = eng; RoF; Drekanoth of Fate; ability; Doom -> $player; intercept $player; 0; 0; 0; 0; 0; 0
It should now work as intended.
