### ISSUE TITLE
Problems with the german letters  ä,ö,ü in Bossnames

### ISSUE THREAD

**Issue by Angormage** [Bamux/Rift-Raid-Alert#2]
The addon seems to have problems with the special german letters ä,ö,ü  when they appear in Boss-Names like Anrak der Üble -> Anrak the Foul
it doesn´t seem to have Problems with this letters in the Names of the casted Spells.

It doesn´t let me translate the triggers for the german client when the name of the caster contains one of the letters I mentioned. Thx in Advance

**Comment by Bamux** [comment]
Schau mal nach in welcher Codierung deine Log.txt und deine RiftRaidAlert.ini gespeichert ist. Hierzu einfach die Datei im Editor öffnen und dann Speichern unter anklicken. Ganz unten siehst du dann die Kodierung. Wichtig ist das beides im UTF-8 Format gespeichert ist. Sag mir bitte bescheid ob das zutrifft dann kann ich den Fehler schon mal ausschließen.

**Comment by Angormage** [comment]
ja sind sie beide.

**Comment by Angormage** [comment]
wie gesagt... es scheint auch nur so zu sein wenn der name des casters einen umlaut enthält. bei spells is das net so. habs in RoF beim ersten Boss getestet.

**Comment by Bamux** [comment]
Die beiden deutschen Trigger für Anrak waren fehlerhaft.

Lad dir nochmal die aktualisierte RiftRaidAlert.ini herunter und geb im Chatfenster
Anrak der Üble -> Stachel der Erde 
ein wenn Siri dann spread out sagt funktioniert alles wie es soll.

**Comment by Angormage** [comment]
funktioniert net, den Rechtschreibfehler bei Stacheln der Erde hab ich selbst korrigiert. Ich denke daß das Problem nicht in der Ini oder der Log.txt liegt. Richtig ausgelesen werden die Skills und auch der Bossname. Hab auch eigene Trigger erstellt und die funktionieren bei allen Bossen ausser bei Anrak. Die Trigger für Guurloth funktionieren auch alle. Es muss etwas mit dem Umlaut im Bossnamen zu Tun haben.

**Comment by Bamux** [comment]
Bei meiner Python Entwicklungsumgebung tritt der Fehler nicht auf wenn ich jedoch die erstellte exe Datei verwende und Großgeschriebene Umlaute (kleine gehen seltsamerweise) verwende bekomme ich eine Fehlermeldung. Hat wohl irgendwas mit der Codierung zu tun ich bin dem Fehler also auf der Spur ;)

**Comment by Bamux** [comment]
Ich habe Version 0.1.4 hochgeladen sollte damit auch mit Umlauten funktionieren.

**Comment by Bamux** [comment]
Achja wär cool wenn du mir die zusätzlichen deutschen Trigger die du erstellt hast geben kannst dann ergänze ich die in der ini Datei. Ich spiel nur mit den englischen Client daher kenne ich die deutschen Bezeichnungen auch nicht.

**Comment by Angormage** [comment]
Super danke. Funktioniert bestens. Habe noch 2 neue Issues gefunden, aber dafür erstell ich neue Threads, daß du sie einzeln bearbeiten kannst. Hier bekommst noch meine anderen Trigger für Anrak. Sie funktionieren alle

trigger = ger; IGP; Anrak the Foul; ability; <- Brüchig; spotten; 0; 0; 0; 3; 0; 0
trigger = ger; IGP; Anrak the Foul; ability; <- remove Brüchig; spotten; 0; 0; 0; -2; 0; 0
trigger = ger; IGP; Anrak the Foul; ability; Anrak der Üble -> Stacheln der Erde; Verteilen; 0; 0; 0; 0; 0; 0
trigger = ger; IGP; Anrak the Foul; ability; Anrak der Üble -> Schwarm von Anrak; Adds kommen; 0; 0; 0; 0; 0; 0
trigger = ger; IGP; Anrak the Foul; ability; Anrak der Üble -> Ruf von Anrak; Adds kommen; 0; 0; 0; 0; 0; 0
trigger = ger; IGP; Anrak the Foul; ability; Anrak der Üble -> Bösartiger Schweifschlag; Vorne weg; 0; 0; 0; 0; 0; 0
trigger = ger; IGP; Anrak the Foul; ability; Anrak der Üble -> Augenstrahl -> $player; intercepten; 0; 0; 8; 0; 0; 0
trigger = ger; IGP; Anrak the Foul; ability; Anrak der Üble -> Bande der Erde; Boss wegziehen; 0; 0; 0; 0; 0; 0
trigger = ger; IGP; Anrak the Foul; ability; $player <- Explosivgift; dispellen; 0; 0; 0; 0; 0; 0

**Comment by Angormage** [comment]
sobald ich einen Boss fertig hab, kriegst von mir  jeweils die kompletten Trigger wenn sie funktionieren.

**Comment by Bamux** [comment]
super danke dir

**Comment by Bamux** [comment]
Welche Text to Speech Stimme benutzt du eigentlich ?

**Comment by Angormage** [comment]
die weibliche Standard Windows stimme, deswegen sind die text to speech ausrufe manchmal etwas komisch, weil ich manche englischen begriffe irgendwie in deutsche lautschrift packen muss.

**Comment by Bamux** [comment]
Schau mal hier nach http://www.mwsreader.com/en/voices/german/ da gibt auch deutsche Stimmen.
Die  IVONA Text to Speech Stimmen sind sehr hochwertig und klingen ziemlich natürlich. Du kannst sie kostenlos für 30 Tage testen. Die kostenlosen Stimmen klingen leider alle sehr roboterhaft.
