### ISSUE TITLE
Probleme mit $player

### ISSUE THREAD

**Issue by Angormage** [Bamux/Rift-Raid-Alert#3]
Hi,
also...
dieser Trigger:
trigger = ger; IGP; Anrak the Foul; ability; <- Brüchig; spotten; 0; 0; 0; 3; 0; 0

sollte eigentlich so aussehen:
trigger = ger; IGP; Anrak the Foul; ability; $player <- Brüchig; spotten; 0; 0; 0; 3; 0; 0

Das Problem ist, wenn ich die eigentliche syntax mit $player verwende, gibt die Sprachausgabe mir statt "spotten" den Namen des Spielers aus. Das Problem ist, daß man eigentlich die richtige syntax verwenden muss, da er sonst ab dem 3. stack von Brüchig bei jedem neuen stack spotten ansagt, auch wenn der tankwechsel schon vollzogen ist.

**Comment by Bamux** [comment]
Den Fehler konnte ich beheben. Ich schau mir noch das andere Problem an dann gib es ein Versionsupdate.

**Comment by Angormage** [comment]
danke dir. funktioniert alles super.
