### ISSUE TITLE
Probleme mit Emotes in denen " gefolgt von Spielernamen vorkommen

### ISSUE THREAD

**Issue by Angormage** [Bamux/Rift-Raid-Alert#4]
Hi,

also...
trigger = ger; IGP; Guurloth; emote; Guurloth schreit: "$player unternimmt gar nichts, oder ihr werdet alle leiden!"; $player stop; 0; 0; 0; 0; 0; 0

funktioniert nicht, weil das addon anscheinend "$player nicht mag. ich habs auch so probiert:

trigger = ger; IGP; Guurloth; emote; $player unternimmt gar nichts; $player stop; 0; 0; 0; 0; 0; 0

da wird der Trigger zwar erkannt aber die Sprachausgabe gibt mir statt dem Spielernamen, Guurloth aus.

**Comment by Bamux** [comment]
Der Fehler ist auch behoben ich uploade gleich Version 0.1.5

**Comment by Angormage** [comment]
danke auch das funktioniert jetzt super. ich mach mich mal an die restlichen bosse von igp und rof ran. die coa bosse kommen dann nach und nach. leider schafft unsere gilde nur ez-mode und da den letzten noch nichtmal.

**Comment by Bamux** [comment]
Die Triggerbezeichnungen in CoA  EZ sollten ja die selben sein wie in den anderen Modi. In welcher Gilde bist du wenn ich fragen darf ?)
Ich bin bei [Abt-Ru-Shin](https://www.youtube.com/channel/UCPORO8UuLMArxKp1tfOFyoA) spiele aber auf dem Server Typhiria.

**Comment by Angormage** [comment]
Ich bin bei <is flauschig> auf Brutwacht. Ich spiel alle Klassen und fast jede Spec. Ich muss leider am Wochenende immer arbeiten deswegen komm ich erst Montag dazu die restlichen Trigger zu machen. Darfst mich gern auch ingame anschreiben. Angormage, Angorwarri, Angorrogue, Angorcleric, Angorprime alle auf Brutwacht.

**Comment by Angormage** [comment]
ok jetzt hats die Gildenbezeichnung rausgelöscht. Bin bei "is flauschig"
