### ISSUE TITLE
Fehler Rift ingame Addon

### ISSUE THREAD

**Issue by Angormage** [Bamux/Rift-Raid-Alert#5]
Bamux, bei mir kommt bei der neuen Version oft der folgende Fehler:

Error: RiftRaidAlert/RiftRaidAlert.lua:115: attempt to index local 'details' (a nil value)
    In RiftRaidAlert / CombatBegin, event Event.System.Secure.Enter
stack traceback:
    [C]: in function '__index'
    RiftRaidAlert/RiftRaidAlert.lua:115: in function <RiftRaidAlert/RiftRaidAlert.lua:107>

**Comment by Bamux** [comment]
Oh ich habe da ein Leerzeichen vergessen hab die RiftRaidAlert.lua geupdatet sollte jetzt gehen.

**Comment by Angormage** [comment]
Danke
