### ISSUE TITLE
False postive when charater names contain keywords

### ISSUE THREAD

**Issue by Paxxie** [Bamux/Rift-Raid-Alert#6]
For example the standard keyword "lfm + rr" is triggered by:
[marroc@zaviel]: lfm tdez need ot/solo heals/400k+dps w specs

To prevent this, may parse the string after "]:"

**Comment by Paxxie** [comment]
Okay, I got a workaround to fix that issue:

keywords = lfm + rr ; attention raid rift
keywords = lfm +  rr; attention raid rift

The solution is to put an extra space before and another one behind "rr", like shown above.

**Comment by Bamux** [comment]
With the next update Rift Raid Alert will track only the words behind the name.
